plugins {
    id 'com.android.application'
}


android {

    namespace 'com.neondrive.game'

    compileSdk 35


    defaultConfig {

        applicationId "com.neondrive.game"

        minSdk 24
        targetSdk 35

        versionCode 1
        versionName "0.1"

        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a"
        }

    }


    buildTypes {

        release {

            minifyEnabled false

        }

    }


    externalNativeBuild {

        cmake {

            path "src/main/cpp/CMakeLists.txt"

        }

    }

}
